### ISSUE TITLE
 Plotconfiguration line mode does not work 

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus_pyqtgraph#13]
The option of configure the line mode in Plotconfiguration tool does not work.

**Comment by cpascual** [comment]
This option comes straight from qwt5 and is not trivially translatable to pyqtgraph.

Still, the step mode can be implemented, but it may require some changes in pyqtgraph itself: https://github.com/pyqtgraph/pyqtgraph/pull/1360

**Comment by cpascual** [comment]
Fixed by #77
