### ISSUE TITLE
Add options -x and -e in 'taurus tpg trend'

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus_pyqtgraph#27]
Manual tests of 'taurus' and 'taurus tpg' (in taurus/doc/how_to_release.md) includes the test of:
```
`taurus tpg trend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
```
However options -x and -e are not still available in 'taurus tpg trend'. Include options -x and -e in 'taurus tpg trend'.

**Comment by cpascual** [comment]
That was a typo in the "how_to_release" document (now fixed).

Where it said "-xe" it should say "-xn". The `-x` option does accept the `n` value, so this can be closed
