### ISSUE TITLE
problem to setmodel 

### ISSUE THREAD

**Issue by hayg25** [taurus-org/taurus_pyqtgraph#3]
Trying the examples, I noticed a problem to use tg_test variables via setModel method. 
For example in taurustrendset.py : 
c2.setModel('sys/tg_test/1/double_scalar')

ValueError: dictionnary update sequence element #0 has length 13; 2 is required

**Comment by cpascual** [comment]
Hi @hayg25 ,

Thanks for reporting!
I reproduced the problem. It comes from an attempt in `taurus_pyqtgraph.TaurusTrendSet._forceRead` to copy a `TangoAttributeValue` object. It can be reproduced with this simple code:

```python
import taurus
import copy
v = taurus.Attribute('sys/tg_test/1/double_scalar').read()  # <-- TangoAttributeValue => FAILS
# v = taurus.Attribute('eval:1').read()  # <-- EvaluationAttrValue => OK
print(v)
w = copy.copy(v) 
```

At first sight, I am inclined to consider this a bug in taurus' `TangoAttributeValue` which IMHO should be copyable... although maybe this is not possible in practice... I'll  check it and report back ASAP

**Comment by cpascual** [comment]
Hi, I confirm that this is actually a bug in taurus, and I proposed a fix in https://github.com/taurus-org/taurus/pull/831 . I am therefore closing this issue. 
Thanks @hayg25 for reporting!
