### ISSUE TITLE
taurus tpg plot: curve names in legend cannot be changed

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus_pyqtgraph#31]
Bug found during manual tests on win10 py3qt5 Jul19 release:

taurus tpg plot: curve names in legend cannot be changed
Even when clicking to 'apply', the curve titles are not changed in the legend

**Comment by mrosanes** [comment]
This option is not yet ready in pyqtgraph

**Comment by cpascual** [comment]
None of the 3 possible methods work yet:
- Plot Configuration dialog --> editing the name of the curve in the list
- Plot Configuration dialog -->"Curve Titles..." button
- Model Selection Dialog, edit title column

**Comment by mariocaptain** [comment]
Is it possible now to change/set the legends of curves in code? In my TaurusTrend panel I have 4 curves, whose data set by the `addModels` method of TaurusTrend and I haven't found a way to change the legends of the models to a more friendly representation in code, other than using the Plot Configuration dialog. Being able to set in code would be much for useful than using the dialog. I have been trying to access the LegendItem objects of the curves in code to set their text to no avail.
Thanks.

**Comment by cpascual** [comment]
>Is it possible now to change/set the legends of curves in code?

Hi, @mariocaptain , you can do it, but it is not trivial. 
Here is a snippet demonstrating it ( adapted from the code in `taurus_pyqtgraph.curveproperties.set_properties_on_curves()`):

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus_pyqtgraph import TaurusPlot
import sys


def change_curve_name(title, curve, plotItem):
    # change curve title
    curve.setData(name=title)
    # update legend (if it exists)
    if plotItem.legend is not None:
        if hasattr(plotItem.legend, "getLabel"):  # requires pyqtgraph > 0.11
            plotItem.legend.getLabel(curve).setText(title)
        else:  # for pyqtgraph <= 0.11
            for sample, label in plotItem.legend.items:
                if sample.item == curve:
                    label.setText(title)
                    break

app = TaurusApplication(cmd_line_parser=None)
w = TaurusPlot()
w.setModel(["eval:rand(33)", "eval:2+rand(33)"])
change_curve_name("foo", w[0], w.getPlotItem())
change_curve_name("bar", w[1], w.getPlotItem())
w.show()
sys.exit(app.exec_())
```

**Comment by mariocaptain** [comment]
Dear @cpascual ,

Thanks so much for the time. The function works very well. I am so happy with TaurusTrend now :)

Best,
Dave
