### ISSUE TITLE
(Win py3qt5) taurus tpg plot: curves cannot be removed 

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus_pyqtgraph#34]
Win py3qt5
taurus 4.5.4-alpha
taurus tpg --version: 0.2.2a0 

taurus tpg plot: curves cannot be removed.

How to reproduce:
Execute:
```
taurus tpg plot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave
```

Right click, and option 'Model XY Chooser' (renamed recently to 'Model selection').

Try to remove one of the models using the dialog of 'Model selection'.
The curves cannot be removed on Windows.

**Comment by cpascual** [comment]
It works fine on debian9 with tpg 0.2.5a
Can you confirm if the bug is still affecting win?

**Comment by mrosanes** [comment]
It works correctly already in the new version of tpg, I close the issue
