### ISSUE TITLE
(Win py3qt5) taurus tpg plot: missing options and icons inside 'Model Selection'

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus_pyqtgraph#35]
Win py3qt5
taurus 4.5.4-alpha
taurus tpg --version: 0.2.2a0

taurus tpg plot: curves cannot be removed.

How to reproduce:
Execute:

taurus tpg plot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave

Right click, and option 'Model XY Chooser' (renamed recently to 'Model selection').

Options (icons) that are present for taurus_pyqtgraph on Debian (adding / removing all/ reordering up / reordering down), are not present on Windows.

**Comment by cpascual** [comment]
> taurus tpg --version: 0.2.2a0 (...)
> Options (icons) that are present for taurus_pyqtgraph on Debian (adding / removing all/ reordering up / reordering down), are not present on Windows.

Those buttons were added in 0.2.3a. Please check again with the latest taurus_pyqtgraph

**Comment by mrosanes** [comment]
Exact; now I tried with version 0.2.4a of taurus_pyqtgraph and missing options are now present; 

Icons are still missing on Win. It can be related with problem on Taurus (tested on 4.6.0) on Win: https://github.com/taurus-org/taurus/issues/975

**Comment by mrosanes** [comment]
I close the ticket, as this issue can be managed through the generic Taurus issue https://github.com/taurus-org/taurus/issues/975
