### ISSUE TITLE
Problem with TaurusPlot setModel

### ISSUE THREAD

**Issue by RomainDl** [taurus-org/taurus_pyqtgraph#40]
Hello,

I’m working on a gui with Taurus Designer and I have a problem with Taurus Plot.

In the ui file, I create a layout for the Plot

In the code, I import TaurusPlot with this :

	from taurus.qt.qtgui.tpg import TaurusPlot

Next, I put my TaurusPlot in the layout  and set the model : 

	plot = TaurusPlot()
	self.Layout.addWidget(plot)
	model = ['myModel']
	plot.setModel(myModel)

Everything works fine when i use 1 model. But I need 2 models for abscissa and curve. I read in the doc that it can be done this way :

	model = ['sys/taurustest/1/abscissas|sys/taurustest/1/curve']

But it’s not working
How can I set the abscissa in my TaurusPlot ?

Thanks for your help !

(Linux, Py3 Qt5, Taurus4.6.1)

Romain Delos
CELIA, Université Bordeaux / France

**Comment by cpascual** [comment]
Hi, @RomainDl , the doc that you maention is for the old (qwt5-based) `TaurusPlot`. 
In the pyqtgraph-based plot, the `setModel()` method accepts a sequence whose member are either ymodel names or tuples of xmodel,ymodel names.


See the following example:
```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.tpg import TaurusPlot

if __name__ == '__main__':
    import sys
    app = TaurusApplication(cmd_line_parser=None)

    w = TaurusPlot()

    model = [
        ('eval:linspace(-1,1,10)','eval:rand(10)'),  # curve 1 defined with xmodel,ymodel tuple
        'eval:arange(10)'  # curve 2 defined with just a ymodel
    ]
    w.setModel(model)

    w.show()
    sys.exit(app.exec_())
```

**Comment by RomainDl** [comment]
Your example solve my problem. Many thanks
