### ISSUE TITLE
Trend: Right click save configuration gives error

### ISSUE THREAD

**Issue by tiagocoutinho** [taurus-org/taurus_pyqtgraph#72]
tested with:
- python 3.7 
- pytango 9.3.1
- taurus 4.7.1-alpha
- taurus_pyqtgraph (latest develop from today)

When I right click on a trend "save configuration" the console shows an error:
```python
Traceback (most recent call last):
  File "/homelocal/opbl04/git/taurus/lib/taurus/qt/qtcore/configuration/configuration.py", line 450, in saveConfigFile
    self.info("Saving current settings in '%s'" % ofile.name)
AttributeError: 'bool' object has no attribute 'name'
```

**Comment by cpascual** [comment]
Fixed with  69fd66b + 571e8cd. Thanks @tiagocoutinho for reporting
